name: test-1.16.5.yml
on:
  workflow_call:

env:
  GITHUB_ACTIONS: true
  RCON_TEST_MC_VERSION: "1.16.5"
  RUST_BACKTRACE: "1"

jobs:
  testing-1-16-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Docker
        run: |
          docker pull ghcr.io/nearlyheadlessjack/mc-test:1.16.5.2
          docker run -d --name mc-test --network host ghcr.io/nearlyheadlessjack/mc-test:1.16.5.2
          sleep 8s

      - name: Run Tests
        run: |
          sleep 3s
          cargo test --test test_docker_rcon_connection -- --test-threads=1
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_list_num -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_list_uuids_num -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_give_item_success -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_give_item_fail -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_gamemode -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_kill -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_msg -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_say -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_title -- --test-threads=1 --nocapture
          sleep 3s
          cargo test --test test_docker_command_with_player -- test_player_tp -- --test-threads=1 --nocapture
