name: test-1.20.1.yml
on:
  workflow_call:

env:
  GITHUB_ACTIONS: true
  RCON_TEST_MC_VERSION: "1.20.1"
  RUST_BACKTRACE: "1"
jobs:
  testing-1-20-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Docker
        run: |
          docker pull ghcr.io/nearlyheadlessjack/mc-test:1.20.1.1
          docker run -d --name mc-test --network host ghcr.io/nearlyheadlessjack/mc-test:1.20.1.1
          sleep 15s
      - name: Download Minecraft-cli-Client
        run: |
          docker pull ghcr.io/nearlyheadlessjack/mc-cli-client:1.0.9
          docker run -d --name mc-cli-1 -e PLAYER_ID=player1 -e MC_PORT=25565 --network host ghcr.io/nearlyheadlessjack/mc-cli-client:1.0.9
          sleep 2s
          docker logs mc-cli-1
          docker run -d --name mc-cli-2 -e PLAYER_ID=player2 -e MC_PORT=25565 --network host ghcr.io/nearlyheadlessjack/mc-cli-client:1.0.9
          sleep 2s
          docker logs mc-cli-2
          docker run -d --name mc-cli-3 -e PLAYER_ID=player3 -e MC_PORT=25565 --network host ghcr.io/nearlyheadlessjack/mc-cli-client:1.0.9
          sleep 2s
          docker logs mc-cli-3
          docker run -d --name mc-cli-4 -e PLAYER_ID=player4 -e MC_PORT=25565 --network host ghcr.io/nearlyheadlessjack/mc-cli-client:1.0.9
          docker logs mc-cli-4

      - name: Setup nextest
        run: |
          cargo install cargo-nextest

      - name: Run Tests
        env:
          NEXTEST_PROFILE: ci
        run: |
          cargo nextest run -- test_docker_rcon_connection 
          cargo nextest run -- test_player
