name: test-1.12.2.yml
on:
  workflow_call:

env:
  GITHUB_ACTIONS: true
  RCON_TEST_MC_VERSION: "1.12.2"
  RUST_BACKTRACE: "1"

jobs:
  testing-1-12-2:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v6

      - name: Setup Docker
        run: |
          docker pull ghcr.io/nearlyheadlessjack/mc-test:1.12.2.3
          docker run -d --name mc-test --network host ghcr.io/nearlyheadlessjack/mc-test:1.12.2.3
          sleep 15s

      - name: Run Rcon Connection Test
        run: |
          cargo test --test test_docker_rcon_connection -- --test-threads=1
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_whitelist_add_not_found -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_kill_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_kick_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_give_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_msg_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_say_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_title_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_tp_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_transfer_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_weather_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_difficulty_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_ban_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_whitelist_operation_none -- --test-threads=1
          sleep 2s
      - name: run command test
        run: |
          cargo test --test test_docker_command_no_player -- test_docker_command_op_none -- --test-threads=1

          
