name: test-1.20.1.yml
on:
  workflow_call:

env:
  GITHUB_ACTIONS: true
  RCON_TEST_MC_VERSION: "1.20.1"
  RUST_BACKTRACE: "1"
jobs:
  testing-1-20-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Docker
        run: |
          docker pull ghcr.io/nearlyheadlessjack/mc-test:1.20.1.0
          docker run -d --name mc-test --network host ghcr.io/nearlyheadlessjack/mc-test:1.20.1.0
          sleep 6s
      - name: Download Minecraft-cli-Client
        run: |
          wget https://github.com/MCCTeam/Minecraft-Console-Client/releases/download/20250522-285/MinecraftClient-20250522-285-linux-x64
          mv MinecraftClient-20250522-285-linux-x64 mc-client
          chmod 777 mc-client
      - name: Running Minecraft-cli-Client
        run: |
          screen -dmS mysession1 bash -c "./mc-client player1 - 127.0.0.1:25565 > script1.log 2>&1"
          screen -dmS mysession2 bash -c "./mc-client player2 - 127.0.0.1:25565 > script2.log 2>&1"
          screen -dmS mysession3 bash -c "./mc-client player3 - 127.0.0.1:25565 > script3.log 2>&1"

      - name: Run Tests
        run: |
          cargo test --test test_docker_rcon_connection  -- --test-threads=1
          cargo test --test test_docker_command_with_player -- --test-threads=1 --nocapture
